SELECT
  O.ID   AS OWNER_ID,
  O.NAME AS OWNER_NAME,
  P.ID   AS PET_ID,
  P.NAME AS PET_NAME
FROM
  OWNER O,
  PET P
WHERE
  O.ID IN (SELECT OWNER_ID
           FROM
             PETS_OWNERS
           WHERE
             PET_ID = P.ID);

SELECT
  O.ID        AS OWNER_ID,
  O.NAME      AS OWNER_NAME,
  PO.PET_ID   AS PET_ID,
  PO.OWNER_ID AS OWNER_ID,
  P.ID        AS PET_ID,
  P.NAME      AS PET_NAME
FROM OWNER O JOIN PETS_OWNERS PO ON (O.ID = PO.OWNER_ID)
  JOIN PET P ON (PO.PET_ID = P.ID);

SELECT *
FROM OWNER O LEFT OUTER JOIN PETS_OWNERS PO ON (O.ID = PO.OWNER_ID)
WHERE PO.PET_ID IS NULL;
    
    
 

        
